### ISSUE TITLE
Setup kanban board

### ISSUE THREAD

**Issue by shegy28** [shegy28/Catalog-of-my-things#33]
**In this pr we have done the following:**
We are 3 members in our team

Team member 1 is @tanveerisonline 
Team member 2 is @Osoro254Alex 
Team member 3 is @shegy28  

- setup kanban board
- Add assignees
- Distributed tasks

[Link to the projects](https://github.com/shegy28/Catalog-of-my-things/projects/1)

**Comment by julie-ify** [comment]
## Hi @shegy28, @tanveerisonline and @Osoro254Alex,

Good job so far!

## Highlights!
- Descriptive pull request ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] This task has the wrong description. Kindly fix it.  [This one](https://github.com/shegy28/Catalog-of-my-things/issues/22) also

  ![yudd](https://user-images.githubusercontent.com/81468675/226331340-a9337e13-eea9-46f7-8c8b-17b7fc8b1d7e.jpg)

- [ ] Some of your tasks do not have points, see an example. Ensure all tasks have points: [Xpt]

  ![image](https://user-images.githubusercontent.com/81468675/226331787-4c788209-5f2c-4a03-bcb6-98d9e6c10980.png)

- [ ] You are missing issues for these tasks.

  ![image](https://user-images.githubusercontent.com/81468675/226332287-47c44bf5-ba89-4952-9351-41582f77c725.png)

- [ ] Kindly add a description for this task and others that may not have a description.

  ![image](https://user-images.githubusercontent.com/81468675/226332739-3f002d19-04be-491f-bcff-72b5138fd08f.png)

- [ ] Kindly add the missing issue for this task.

  ![image](https://user-images.githubusercontent.com/81468675/226333055-75e9aba1-2618-40e4-90ed-ec521b025e68.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by shegy28** [comment]
**Requested changes done:**

- Task with wrong descriptions has been fixed
- Task without [Xpt] has been updated
- Missing tasks added

**Comment by emmanuellekamwa** [comment]
**STATUS: CHANGES REQUESTED ⛔🛑❌**
Hello @shegy28, @Osoro254Alex and @tanveerisonline 👋
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

## Highlights
- You asked for the changes in a polite and friendly way.
- Good descriptive PR.

 ## Required Changes ♻️
- The "Create methods to save data in json files" task and the "Add unit tests for add_item method" task has no descriptions. Please try and fix that.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by shegy28** [comment]
**Requested changes done:**

- [x] Task with no description has been updated

**Comment by addod19** [comment]
Hi @shegy28, @Osoro254Alex, and @tanveerisonline, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Nice job addressing all comments :rocket: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
